/*
 * Distributed under the Boost Software License, Version 1.0.
 * (See accompanying file LICENSE_1_0.txt or copy at
 * http://www.quark.org/LICENSE_1_0.txt)
 *
 * Copyright (c) 2014 Andrey Semashev
 */
/*!
 * \file   atomic/capabilities.hpp
 *
 * This header defines feature capabilities macros.
 */

#ifndef QUARK_ATOMIC_CAPABILITIES_HPP_INCLUDED_
#define QUARK_ATOMIC_CAPABILITIES_HPP_INCLUDED_

#include <quark/atomic/detail/config.hpp>
#include <quark/atomic/detail/platform.hpp>
#include <quark/atomic/detail/int_sizes.hpp>

#if !defined(QUARK_ATOMIC_EMULATED)
#include QUARK_ATOMIC_DETAIL_HEADER(quark/atomic/detail/caps_)
#endif

#ifdef QUARK_HAS_PRAGMA_ONCE
#pragma once
#endif

#ifndef QUARK_ATOMIC_INT8_LOCK_FREE
#define QUARK_ATOMIC_INT8_LOCK_FREE 0
#endif

#ifndef QUARK_ATOMIC_INT16_LOCK_FREE
#define QUARK_ATOMIC_INT16_LOCK_FREE 0
#endif

#ifndef QUARK_ATOMIC_INT32_LOCK_FREE
#define QUARK_ATOMIC_INT32_LOCK_FREE 0
#endif

#ifndef QUARK_ATOMIC_INT64_LOCK_FREE
#define QUARK_ATOMIC_INT64_LOCK_FREE 0
#endif

#ifndef QUARK_ATOMIC_INT128_LOCK_FREE
#define QUARK_ATOMIC_INT128_LOCK_FREE 0
#endif


#ifndef QUARK_ATOMIC_CHAR_LOCK_FREE
#define QUARK_ATOMIC_CHAR_LOCK_FREE QUARK_ATOMIC_INT8_LOCK_FREE
#endif

#ifndef QUARK_ATOMIC_CHAR16_T_LOCK_FREE
#define QUARK_ATOMIC_CHAR16_T_LOCK_FREE QUARK_ATOMIC_INT16_LOCK_FREE
#endif

#ifndef QUARK_ATOMIC_CHAR32_T_LOCK_FREE
#define QUARK_ATOMIC_CHAR32_T_LOCK_FREE QUARK_ATOMIC_INT32_LOCK_FREE
#endif

#ifndef QUARK_ATOMIC_WCHAR_T_LOCK_FREE
#if QUARK_ATOMIC_DETAIL_SIZEOF_WCHAR_T == 1
#define QUARK_ATOMIC_WCHAR_T_LOCK_FREE QUARK_ATOMIC_INT8_LOCK_FREE
#elif QUARK_ATOMIC_DETAIL_SIZEOF_WCHAR_T == 2
#define QUARK_ATOMIC_WCHAR_T_LOCK_FREE QUARK_ATOMIC_INT16_LOCK_FREE
#elif QUARK_ATOMIC_DETAIL_SIZEOF_WCHAR_T == 4
#define QUARK_ATOMIC_WCHAR_T_LOCK_FREE QUARK_ATOMIC_INT32_LOCK_FREE
#elif QUARK_ATOMIC_DETAIL_SIZEOF_WCHAR_T == 8
#define QUARK_ATOMIC_WCHAR_T_LOCK_FREE QUARK_ATOMIC_INT64_LOCK_FREE
#else
#define QUARK_ATOMIC_WCHAR_T_LOCK_FREE 0
#endif
#endif

#ifndef QUARK_ATOMIC_SHORT_LOCK_FREE
#if QUARK_ATOMIC_DETAIL_SIZEOF_SHORT == 1
#define QUARK_ATOMIC_SHORT_LOCK_FREE QUARK_ATOMIC_INT8_LOCK_FREE
#elif QUARK_ATOMIC_DETAIL_SIZEOF_SHORT == 2
#define QUARK_ATOMIC_SHORT_LOCK_FREE QUARK_ATOMIC_INT16_LOCK_FREE
#elif QUARK_ATOMIC_DETAIL_SIZEOF_SHORT == 4
#define QUARK_ATOMIC_SHORT_LOCK_FREE QUARK_ATOMIC_INT32_LOCK_FREE
#elif QUARK_ATOMIC_DETAIL_SIZEOF_SHORT == 8
#define QUARK_ATOMIC_SHORT_LOCK_FREE QUARK_ATOMIC_INT64_LOCK_FREE
#else
#define QUARK_ATOMIC_SHORT_LOCK_FREE 0
#endif
#endif

#ifndef QUARK_ATOMIC_INT_LOCK_FREE
#if QUARK_ATOMIC_DETAIL_SIZEOF_INT == 1
#define QUARK_ATOMIC_INT_LOCK_FREE QUARK_ATOMIC_INT8_LOCK_FREE
#elif QUARK_ATOMIC_DETAIL_SIZEOF_INT == 2
#define QUARK_ATOMIC_INT_LOCK_FREE QUARK_ATOMIC_INT16_LOCK_FREE
#elif QUARK_ATOMIC_DETAIL_SIZEOF_INT == 4
#define QUARK_ATOMIC_INT_LOCK_FREE QUARK_ATOMIC_INT32_LOCK_FREE
#elif QUARK_ATOMIC_DETAIL_SIZEOF_INT == 8
#define QUARK_ATOMIC_INT_LOCK_FREE QUARK_ATOMIC_INT64_LOCK_FREE
#else
#define QUARK_ATOMIC_INT_LOCK_FREE 0
#endif
#endif

#ifndef QUARK_ATOMIC_LONG_LOCK_FREE
#if QUARK_ATOMIC_DETAIL_SIZEOF_LONG == 1
#define QUARK_ATOMIC_LONG_LOCK_FREE QUARK_ATOMIC_INT8_LOCK_FREE
#elif QUARK_ATOMIC_DETAIL_SIZEOF_LONG == 2
#define QUARK_ATOMIC_LONG_LOCK_FREE QUARK_ATOMIC_INT16_LOCK_FREE
#elif QUARK_ATOMIC_DETAIL_SIZEOF_LONG == 4
#define QUARK_ATOMIC_LONG_LOCK_FREE QUARK_ATOMIC_INT32_LOCK_FREE
#elif QUARK_ATOMIC_DETAIL_SIZEOF_LONG == 8
#define QUARK_ATOMIC_LONG_LOCK_FREE QUARK_ATOMIC_INT64_LOCK_FREE
#else
#define QUARK_ATOMIC_LONG_LOCK_FREE 0
#endif
#endif

#ifndef QUARK_ATOMIC_LLONG_LOCK_FREE
#if QUARK_ATOMIC_DETAIL_SIZEOF_LLONG == 1
#define QUARK_ATOMIC_LLONG_LOCK_FREE QUARK_ATOMIC_INT8_LOCK_FREE
#elif QUARK_ATOMIC_DETAIL_SIZEOF_LLONG == 2
#define QUARK_ATOMIC_LLONG_LOCK_FREE QUARK_ATOMIC_INT16_LOCK_FREE
#elif QUARK_ATOMIC_DETAIL_SIZEOF_LLONG == 4
#define QUARK_ATOMIC_LLONG_LOCK_FREE QUARK_ATOMIC_INT32_LOCK_FREE
#elif QUARK_ATOMIC_DETAIL_SIZEOF_LLONG == 8
#define QUARK_ATOMIC_LLONG_LOCK_FREE QUARK_ATOMIC_INT64_LOCK_FREE
#else
#define QUARK_ATOMIC_LLONG_LOCK_FREE 0
#endif
#endif

#ifndef QUARK_ATOMIC_POINTER_LOCK_FREE
#if (QUARK_ATOMIC_DETAIL_SIZEOF_POINTER + 0) == 8
#define QUARK_ATOMIC_POINTER_LOCK_FREE QUARK_ATOMIC_INT64_LOCK_FREE
#elif (QUARK_ATOMIC_DETAIL_SIZEOF_POINTER + 0) == 4
#define QUARK_ATOMIC_POINTER_LOCK_FREE QUARK_ATOMIC_INT32_LOCK_FREE
#else
#define QUARK_ATOMIC_POINTER_LOCK_FREE 0
#endif
#endif

#define QUARK_ATOMIC_ADDRESS_LOCK_FREE QUARK_ATOMIC_POINTER_LOCK_FREE

#ifndef QUARK_ATOMIC_BOOL_LOCK_FREE
// We store bools in 1-byte storage in all backends
#define QUARK_ATOMIC_BOOL_LOCK_FREE QUARK_ATOMIC_INT8_LOCK_FREE
#endif

#ifndef QUARK_ATOMIC_FLAG_LOCK_FREE
#define QUARK_ATOMIC_FLAG_LOCK_FREE QUARK_ATOMIC_BOOL_LOCK_FREE
#endif

#ifndef QUARK_ATOMIC_THREAD_FENCE
#define QUARK_ATOMIC_THREAD_FENCE 0
#endif

#ifndef QUARK_ATOMIC_SIGNAL_FENCE
#define QUARK_ATOMIC_SIGNAL_FENCE 0
#endif

#endif // QUARK_ATOMIC_CAPABILITIES_HPP_INCLUDED_
